---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      # Install Docker
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          DOCKER_COMPOSE_VERSION=1.29.2  # Specify the desired version here
          sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # Check Docker version
      - name: Check Docker version
        run: docker --version

      # Check Docker Compose version
      - name: Check Docker Compose version
        run: docker-compose --version

      # Run Tests
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"

      # Run Lint
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8 --ignore=E126,E131,E275,E203,E122,W391,F401,E225,E231,E302,E391,E261,E262,W293,E251,E303,E305"
